const videos = [
  {
    id: 1,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 2,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 3,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 4,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 5,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 6,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 7,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
  {
    id: 8,
    title: 'FEED | Creating a Social media with React.js',
    channel: 'Lucas Melo',
    views: '11 mi',
    date: '1 week',
    avatar: '/assets/thumb1.png',
    thumb: '/assets/thumb1.png',
  },
];

export default videos;